services:
  - type: web
    name: recipe-extractor-v2
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-db-v2
          property: connectionString
      - key: DEBUG
        value: False
      - key: PORT
        value: 10000
    
databases:
  - name: recipe-db-v2
    databaseName: recipes_v2
    user: recipe_user_v2
    plan: free